apiVersion: v1
kind: Service
metadata:
  name: bfa-service
  labels:
    app: flask_app
    run: flask_app-service
spec:
  # Метод для открытия порта
  type: NodePort
  ports:
  - port: 5000
    protocol: TCP
  # Селектор, по которому выбираются целевые поды
  selector:
    app: flask_app