apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: rsvp-db
spec:
  replicas: 1
  template:
    metadata:
      labels:
        appdb: rsvpdb
    spec:
      containers:
      - name: rsvpd-db
        image: mongo:3.3
        env:
          # Переменная окружения, с помощью которой другие программы могут получить IP-адрес данного пода
        - name: MONGODB_DATABASE
          value: rsvpdata
        ports:
        - containerPort: 27017